#<% require 'kitchen-sync' %>
---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 2048
    cpus: 2
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  roles_path: roles
  environments_path: environments
  data_bags_path: data_bags
  cookbook_path: ["cookbooks", "site-cookbooks"]
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
###### Server type suites ######

  - name: base
    run_list:
      - role[base]
    attributes: {}

###### Cookbook suites ######
